services:
  mqtt:
    image: efrecon/mosquitto:1.5.5
    restart: unless-stopped
#    environment:
#      - MOSQUITTO_INCLUDE_DIR=/mosquitto/config/sections/
#      - MOSQUITTO__PERSISTENCE__AUTOSAVE_ON_CHANGES=true
#      - MOSQUITTO__PERSISTENCE__AUTOSAVE_INTERVAL=100
#      - MOSQUITTO__PERSISTENCE__PERSISTENCE=true
#      - MOSQUITTO__PERSISTENCE__PERSISTENCE_LOCATION=/mosquitto/data/
#      - MOSQUITTO__LOGGING__LOG_DEST=stderr
    ports:
      - 1883:1883
