services:
  mqtt:
    image: efrecon/mosquitto:1.5.5
    restart: unless-stopped
    ports:
      - 1883:1883
  hbcigateway:
    build:
      context: hbcigateway
      dockerfile: Dockerfile
    environment:
      BONK_MQTT_URL: tcp://mqtt:1883
      BONK_MQTT_ID: "3fc620d0-8f13-433d-beb7-ee22b234101b"
    depends_on:
      - mqtt
